// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeCQUmDlvQGTN09RRnIenx3UpobX2hA5w',
    appId: '1:509685715671:web:d8bc25a67f70b3041dd692',
    messagingSenderId: '509685715671',
    projectId: 'sanity-chat',
    authDomain: 'sanity-chat.firebaseapp.com',
    storageBucket: 'sanity-chat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmr9unUvucDJZa_EHs-tIZvWI-aA7ZcMw',
    appId: '1:509685715671:android:04a7847081ff995d1dd692',
    messagingSenderId: '509685715671',
    projectId: 'sanity-chat',
    storageBucket: 'sanity-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFScyjMUp1dqdCIwfJDIcQQsTgdsBF54Q',
    appId: '1:509685715671:ios:8517a5436be302f11dd692',
    messagingSenderId: '509685715671',
    projectId: 'sanity-chat',
    storageBucket: 'sanity-chat.firebasestorage.app',
    iosBundleId: 'com.example.safeChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFScyjMUp1dqdCIwfJDIcQQsTgdsBF54Q',
    appId: '1:509685715671:ios:8517a5436be302f11dd692',
    messagingSenderId: '509685715671',
    projectId: 'sanity-chat',
    storageBucket: 'sanity-chat.firebasestorage.app',
    iosBundleId: 'com.example.safeChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeCQUmDlvQGTN09RRnIenx3UpobX2hA5w',
    appId: '1:509685715671:web:82f38f70206ff4be1dd692',
    messagingSenderId: '509685715671',
    projectId: 'sanity-chat',
    authDomain: 'sanity-chat.firebaseapp.com',
    storageBucket: 'sanity-chat.firebasestorage.app',
  );
}
